In [31]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [32]:
tf.__version__

'2.6.0'

In [33]:
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [34]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [35]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

every feature is numeric, no categories hence, encoding is not needed

In [36]:
x[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 82)
y_test

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
      dtype=int64)

# feature scaling is must for deep learning 

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# initializing the ann

In [39]:
ann = tf.keras.models.Sequential()

# adding input and first hidden layer

In [40]:
ann.add(tf.keras.layers.Dense(units = 12,activation = 'relu'))

# adding the other layers

In [41]:
ann.add(tf.keras.layers.Dense(units = 36,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 64,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 12,activation = 'relu'))

it's better to build a conical units in hidden layers to improve accuracy and for better training performance

# adding the output layer

In [42]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

# compiling the ann

In [43]:
ann.compile(optimizer = 'adam',metrics = ['accuracy'],loss = 'binary_crossentropy')

# training the ann on training set

In [44]:
ann.fit(x_train,y_train,batch_size = 32, epochs = 100)

Epoch 1/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6511 - accuracy: 0.6515
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5983 - accuracy: 0.6743
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5579 - accuracy: 0.7313
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5304 - accuracy: 0.7573
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5126 - accuracy: 0.7541
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4993 - accuracy: 0.7524
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4885 - accuracy: 0.7736
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4767 - accuracy: 0.7818
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4709 - accuracy: 0.7850
Epoch 10/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4714 - accuracy: 0.7834
Epoch 11/

20/20 [==============================] - 0s 3ms/step - loss: 0.2474 - accuracy: 0.8990
Epoch 84/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2419 - accuracy: 0.9007
Epoch 85/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2382 - accuracy: 0.9137
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2254 - accuracy: 0.9202
Epoch 87/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2264 - accuracy: 0.9121
Epoch 88/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2272 - accuracy: 0.9137
Epoch 89/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2241 - accuracy: 0.9251
Epoch 90/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2209 - accuracy: 0.9218
Epoch 91/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2222 - accuracy: 0.9169
Epoch 92/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2175 - accuracy: 0.9088
Epoch 93/100


# predicting test set

In [48]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]

# confusion matrix

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[88 19]
 [20 27]]


0.7467532467532467